services:
  - type: web
    name: rapidrescue-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: DATABASE_URL
        sync: false  # You must provide this value manually in your Render dashboard!
      - key: SECRET_KEY
        generateValue: true
